// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pagedraft.Api.Data;

#nullable disable

namespace Pagedraft.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260319160529_AddAnalysisRunLog")]
    partial class AddAnalysisRunLog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Pagedraft.Api.Models.AnalysisResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AnalysisType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid?>("BookId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChapterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("JobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Language")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("he");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PromptUsed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ProofreadNoChangesHint")
                        .HasColumnType("bit");

                    b.Property<string>("ResultText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("SceneId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SourceTextSnapshot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("StructuredResult")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("TemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ChapterId");

                    b.HasIndex("TemplateId");

                    b.HasIndex("BookId", "Scope", "AnalysisType");

                    b.ToTable("AnalysisResults");
                });

            modelBuilder.Entity("Pagedraft.Api.Models.AnalysisRunLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AnalysisResultId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AnalysisType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid?>("BookId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ChapterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChunkDetailsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("FallbackChunks")
                        .HasColumnType("int");

                    b.Property<int>("InputCharCount")
                        .HasColumnType("int");

                    b.Property<int>("InputWordCount")
                        .HasColumnType("int");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("NoChangesHint")
                        .HasColumnType("bit");

                    b.Property<int>("OutputCharCount")
                        .HasColumnType("int");

                    b.Property<Guid?>("PromptTemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SceneId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SucceededChunks")
                        .HasColumnType("int");

                    b.Property<int>("SuggestionCount")
                        .HasColumnType("int");

                    b.Property<int>("TotalChunks")
                        .HasColumnType("int");

                    b.Property<long>("TotalDurationMs")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisResultId");

                    b.HasIndex("JobId");

                    b.HasIndex("PromptTemplateId");

                    b.ToTable("AnalysisRunLogs", (string)null);
                });

            modelBuilder.Entity("Pagedraft.Api.Models.AnalysisSuggestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AnalysisResultId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ContextAfter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContextBefore")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("EndOffset")
                        .HasColumnType("int");

                    b.Property<string>("Explanation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<string>("OriginalText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Outcome")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Reason")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("StartOffset")
                        .HasColumnType("int");

                    b.Property<string>("SuggestedText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisResultId");

                    b.ToTable("AnalysisSuggestions");
                });

            modelBuilder.Entity("Pagedraft.Api.Models.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Author")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("Pagedraft.Api.Models.BookBible", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CharacterRegisterJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("StyleProfileJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThemesJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimelineJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("WorldBuildingJson")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BookId")
                        .IsUnique();

                    b.ToTable("BookBibles");
                });

            modelBuilder.Entity("Pagedraft.Api.Models.BookProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CharactersJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Genre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("LanguageRegister")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LiteratureLevel")
                        .HasColumnType("int");

                    b.Property<string>("StoryStructureJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubGenre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Synopsis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TargetAudience")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("BookId")
                        .IsUnique();

                    b.ToTable("BookProfiles");
                });

            modelBuilder.Entity("Pagedraft.Api.Models.Chapter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentSfdt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContentText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("PartName")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("WordCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookId", "Order")
                        .IsUnique();

                    b.ToTable("Chapters");
                });

            modelBuilder.Entity("Pagedraft.Api.Models.ChunkSummary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChapterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("StructuredJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SummaryText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ChapterId");

                    b.HasIndex("BookId", "ChapterId")
                        .IsUnique();

                    b.ToTable("ChunkSummaries");
                });

            modelBuilder.Entity("Pagedraft.Api.Models.DocumentVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AnalysisResultId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChapterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentSfdt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Label")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("OriginalText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("SceneId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SuggestedText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("SuggestionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BookId", "ChapterId", "SceneId");

                    b.ToTable("DocumentVersions");
                });

            modelBuilder.Entity("Pagedraft.Api.Models.PromptTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsBuiltIn")
                        .HasColumnType("bit");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TemplateText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("PromptTemplates");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111101"),
                            IsBuiltIn = true,
                            Language = "he",
                            Name = "הגהה",
                            TemplateText = "בדוק את הטקסט הבא ומצא שגיאות כתיב, דקדוק, ופיסוק:\n\n{chapter_text}",
                            Type = "Proofreading"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111102"),
                            IsBuiltIn = true,
                            Language = "he",
                            Name = "ניתוח ספרותי",
                            TemplateText = "נתח את הפרק הבא מבחינה ספרותית (דמויות, עלילה, מוטיבים, שפה):\n\n{chapter_text}",
                            Type = "Literary"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111103"),
                            IsBuiltIn = true,
                            Language = "he",
                            Name = "ניתוח לשוני",
                            TemplateText = "נתח את הפרק הבא מבחינה לשונית (דקדוק, סגנון, אוצר מילים):\n\n{chapter_text}",
                            Type = "Linguistic"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111104"),
                            IsBuiltIn = true,
                            Language = "he",
                            Name = "מותאם אישית",
                            TemplateText = "{chapter_text}",
                            Type = "Custom"
                        });
                });

            modelBuilder.Entity("Pagedraft.Api.Models.Scene", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChapterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentSfdt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ChapterId", "Order")
                        .IsUnique();

                    b.ToTable("Scenes");
                });

            modelBuilder.Entity("Pagedraft.Api.Models.SceneEmbedding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChapterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Dimensions")
                        .HasColumnType("int");

                    b.Property<byte[]>("EmbeddingVector")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("SceneId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("ChapterId");

                    b.HasIndex("SceneId");

                    b.ToTable("SceneEmbeddings");
                });

            modelBuilder.Entity("Pagedraft.Api.Models.SuggestionOutcomeRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AnalysisResultId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("OriginalText")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SuggestedText")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisResultId", "OriginalText", "SuggestedText")
                        .IsUnique();

                    b.ToTable("SuggestionOutcomeRecords");
                });

            modelBuilder.Entity("Pagedraft.Api.Models.AnalysisResult", b =>
                {
                    b.HasOne("Pagedraft.Api.Models.Chapter", "Chapter")
                        .WithMany("AnalysisResults")
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pagedraft.Api.Models.PromptTemplate", "Template")
                        .WithMany("Results")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Chapter");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("Pagedraft.Api.Models.AnalysisRunLog", b =>
                {
                    b.HasOne("Pagedraft.Api.Models.AnalysisResult", "AnalysisResult")
                        .WithMany()
                        .HasForeignKey("AnalysisResultId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Pagedraft.Api.Models.PromptTemplate", "PromptTemplate")
                        .WithMany()
                        .HasForeignKey("PromptTemplateId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AnalysisResult");

                    b.Navigation("PromptTemplate");
                });

            modelBuilder.Entity("Pagedraft.Api.Models.AnalysisSuggestion", b =>
                {
                    b.HasOne("Pagedraft.Api.Models.AnalysisResult", "AnalysisResult")
                        .WithMany("Suggestions")
                        .HasForeignKey("AnalysisResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnalysisResult");
                });

            modelBuilder.Entity("Pagedraft.Api.Models.BookBible", b =>
                {
                    b.HasOne("Pagedraft.Api.Models.Book", "Book")
                        .WithOne()
                        .HasForeignKey("Pagedraft.Api.Models.BookBible", "BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("Pagedraft.Api.Models.BookProfile", b =>
                {
                    b.HasOne("Pagedraft.Api.Models.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("Pagedraft.Api.Models.Chapter", b =>
                {
                    b.HasOne("Pagedraft.Api.Models.Book", "Book")
                        .WithMany("Chapters")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("Pagedraft.Api.Models.ChunkSummary", b =>
                {
                    b.HasOne("Pagedraft.Api.Models.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pagedraft.Api.Models.Chapter", "Chapter")
                        .WithMany()
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Chapter");
                });

            modelBuilder.Entity("Pagedraft.Api.Models.Scene", b =>
                {
                    b.HasOne("Pagedraft.Api.Models.Chapter", "Chapter")
                        .WithMany("Scenes")
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chapter");
                });

            modelBuilder.Entity("Pagedraft.Api.Models.SceneEmbedding", b =>
                {
                    b.HasOne("Pagedraft.Api.Models.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pagedraft.Api.Models.Chapter", "Chapter")
                        .WithMany()
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pagedraft.Api.Models.Scene", "Scene")
                        .WithMany()
                        .HasForeignKey("SceneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Chapter");

                    b.Navigation("Scene");
                });

            modelBuilder.Entity("Pagedraft.Api.Models.SuggestionOutcomeRecord", b =>
                {
                    b.HasOne("Pagedraft.Api.Models.AnalysisResult", "AnalysisResult")
                        .WithMany()
                        .HasForeignKey("AnalysisResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnalysisResult");
                });

            modelBuilder.Entity("Pagedraft.Api.Models.AnalysisResult", b =>
                {
                    b.Navigation("Suggestions");
                });

            modelBuilder.Entity("Pagedraft.Api.Models.Book", b =>
                {
                    b.Navigation("Chapters");
                });

            modelBuilder.Entity("Pagedraft.Api.Models.Chapter", b =>
                {
                    b.Navigation("AnalysisResults");

                    b.Navigation("Scenes");
                });

            modelBuilder.Entity("Pagedraft.Api.Models.PromptTemplate", b =>
                {
                    b.Navigation("Results");
                });
#pragma warning restore 612, 618
        }
    }
}
